/* global PCL */
window.PCL = window.PCL || {};

PCL.DATA = {

  /* ========================================
     TEAMS  (8 PCL Teams)
  ======================================== */
  teams: [
    {
      id: 'anand-arrows',
      name: 'Anand Arrows',
      shortName: 'AA',
      color: '#2563eb',
      color2: '#fcd34d',
      emoji: '🏹',
      homeGround: 'Anand Sports Complex, Anand',
      captain: 'Vikram Patel',
      coach: 'Dhirubhai Amin',
      titles: 2,
      titleYears: [2022, 2024],
      founded: 2020,
      desc: 'The Anand Arrows are the most successful side in PCL history, having claimed back-to-back titles in 2022 and 2024 under the inspired captaincy of Vikram Patel.',
      players: [
        { id:'aa1', name:'Vikram Patel',    role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:true,  isWK:false, avatar:'👑', stats:{m:14,r:612,avg:51.0,sr:148.5,w:0,eco:0}   },
        { id:'aa2', name:'Rohan Patel',     role:'Batter',       bat:'Left-hand',  bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:14,r:498,avg:38.3,sr:139.2,w:0,eco:0}   },
        { id:'aa3', name:'Jigar Shah',      role:'Batter',       bat:'Right-hand', bowl:'Right-arm Off-spin', isCaptain:false, isWK:false, avatar:'🏏', stats:{m:14,r:412,avg:34.3,sr:131.0,w:5,eco:7.8} },
        { id:'aa4', name:'Dhruv Amin',      role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:12,r:298,avg:27.1,sr:124.6,w:0,eco:0}   },
        { id:'aa5', name:'Kush Modi',       role:'All-rounder',  bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'⭐', stats:{m:14,r:267,avg:24.3,sr:142.5,w:12,eco:8.4} },
        { id:'aa6', name:'Mihir Joshi',     role:'Wicket-keeper',bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:true,  avatar:'🧤', stats:{m:14,r:180,avg:22.5,sr:128.0,w:0,eco:0}   },
        { id:'aa7', name:'Parth Trivedi',   role:'All-rounder',  bat:'Left-hand',  bowl:'Left-arm Spin',      isCaptain:false, isWK:false, avatar:'⭐', stats:{m:13,r:198,avg:19.8,sr:118.0,w:15,eco:7.2} },
        { id:'aa8', name:'Neel Mehta',      role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:14,r:42,avg:8.4,sr:105.0,w:21,eco:7.9}  },
        { id:'aa9', name:'Raj Chaudhary',   role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:12,r:38,avg:6.3,sr:95.0,w:17,eco:8.1}   },
        { id:'aa10',name:'Vipul Solanki',   role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Leg-spin', isCaptain:false, isWK:false, avatar:'🌀', stats:{m:14,r:25,avg:5.0,sr:78.0,w:18,eco:6.8}   },
        { id:'aa11',name:'Harsh Panchal',   role:'Bowler',       bat:'Left-hand',  bowl:'Left-arm Spin',      isCaptain:false, isWK:false, avatar:'🌀', stats:{m:11,r:19,avg:3.8,sr:70.0,w:11,eco:7.0}   },
        { id:'aa12',name:'Dev Prajapati',   role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:8,r:187,avg:26.7,sr:130.0,w:0,eco:0}    },
        { id:'aa13',name:'Sagar Nayak',     role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:9,r:12,avg:4.0,sr:60.0,w:10,eco:8.5}    },
        { id:'aa14',name:'Aakash Raval',    role:'All-rounder',  bat:'Left-hand',  bowl:'Left-arm Fast',      isCaptain:false, isWK:false, avatar:'⭐', stats:{m:7,r:112,avg:18.7,sr:115.0,w:6,eco:8.9}   },
        { id:'aa15',name:'Chirag Thakkar',  role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:6,r:142,avg:23.7,sr:140.0,w:0,eco:0}    },
      ]
    },
    {
      id: 'surat-smashers',
      name: 'Surat Smashers',
      shortName: 'SS',
      color: '#ea580c',
      color2: '#0f172a',
      emoji: '🔥',
      homeGround: 'Diamond City Arena, Surat',
      captain: 'Kiran Desai',
      coach: 'Ramesh Joshi',
      titles: 1,
      titleYears: [2023],
      founded: 2020,
      desc: 'Surat Smashers are known for their explosive batting lineup. They clinched the PCL title in 2023 on the back of Kiran Desai\'s record-breaking innings.',
      players: [
        { id:'ss1', name:'Kiran Desai',     role:'Batter',       bat:'Left-hand',  bowl:'N/A',                isCaptain:true,  isWK:false, avatar:'👑', stats:{m:14,r:589,avg:49.1,sr:162.0,w:0,eco:0}   },
        { id:'ss2', name:'Manav Joshi',     role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:14,r:421,avg:35.1,sr:145.0,w:0,eco:0}   },
        { id:'ss3', name:'Preet Shah',      role:'Batter',       bat:'Right-hand', bowl:'Right-arm Off-spin', isCaptain:false, isWK:false, avatar:'🏏', stats:{m:12,r:347,avg:31.5,sr:133.0,w:4,eco:7.5} },
        { id:'ss4', name:'Tushar Patel',    role:'Wicket-keeper',bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:true,  avatar:'🧤', stats:{m:14,r:212,avg:21.2,sr:120.0,w:0,eco:0}   },
        { id:'ss5', name:'Kunal Modi',      role:'All-rounder',  bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'⭐', stats:{m:14,r:234,avg:26.0,sr:139.0,w:14,eco:8.2} },
        { id:'ss6', name:'Aryan Mehta',     role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:14,r:29,avg:5.8,sr:88.0,w:23,eco:7.6}   },
        { id:'ss7', name:'Sunny Amin',      role:'Bowler',       bat:'Left-hand',  bowl:'Left-arm Fast',      isCaptain:false, isWK:false, avatar:'🎯', stats:{m:13,r:31,avg:6.2,sr:92.0,w:19,eco:8.3}   },
        { id:'ss8', name:'Yash Trivedi',    role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Leg-spin', isCaptain:false, isWK:false, avatar:'🌀', stats:{m:14,r:18,avg:3.6,sr:69.0,w:16,eco:7.1}   },
        { id:'ss9', name:'Om Chaudhary',    role:'Batter',       bat:'Left-hand',  bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:11,r:278,avg:30.9,sr:128.0,w:0,eco:0}   },
        { id:'ss10',name:'Raj Solanki',     role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:10,r:15,avg:3.0,sr:65.0,w:12,eco:8.7}   },
        { id:'ss11',name:'Hari Panchal',    role:'All-rounder',  bat:'Right-hand', bowl:'Right-arm Off-spin', isCaptain:false, isWK:false, avatar:'⭐', stats:{m:12,r:167,avg:18.6,sr:116.0,w:9,eco:7.4}  },
        { id:'ss12',name:'Jay Prajapati',   role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:8,r:176,avg:25.1,sr:132.0,w:0,eco:0}    },
        { id:'ss13',name:'Dax Nayak',       role:'Bowler',       bat:'Left-hand',  bowl:'Left-arm Spin',      isCaptain:false, isWK:false, avatar:'🌀', stats:{m:9,r:11,avg:2.8,sr:61.0,w:8,eco:6.9}     },
        { id:'ss14',name:'Veer Raval',      role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:7,r:9,avg:3.0,sr:56.0,w:7,eco:8.8}      },
        { id:'ss15',name:'Kabir Thakkar',   role:'Batter',       bat:'Left-hand',  bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:6,r:118,avg:23.6,sr:137.0,w:0,eco:0}    },
      ]
    },
    {
      id: 'vadodara-valiants',
      name: 'Vadodara Valiants',
      shortName: 'VV',
      color: '#7c3aed',
      color2: '#f0fdf4',
      emoji: '⚡',
      homeGround: 'Sayaji Baug Stadium, Vadodara',
      captain: 'Nitin Shah',
      coach: 'Prakash Mehta',
      titles: 0,
      titleYears: [],
      founded: 2020,
      desc: 'Vadodara Valiants are a young and ambitious squad looking to break their title drought. With a talented core, they\'re the team everyone loves to watch.',
      players: [
        { id:'vv1', name:'Nitin Shah',      role:'Batter',       bat:'Right-hand', bowl:'Right-arm Off-spin', isCaptain:true,  isWK:false, avatar:'👑', stats:{m:14,r:453,avg:37.8,sr:136.0,w:3,eco:7.9} },
        { id:'vv2', name:'Akash Desai',     role:'Batter',       bat:'Left-hand',  bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:14,r:387,avg:32.3,sr:143.0,w:0,eco:0}   },
        { id:'vv3', name:'Bhavan Joshi',    role:'All-rounder',  bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'⭐', stats:{m:14,r:245,avg:22.3,sr:130.0,w:11,eco:8.6} },
        { id:'vv4', name:'Suresh Patel',    role:'Wicket-keeper',bat:'Left-hand',  bowl:'N/A',                isCaptain:false, isWK:true,  avatar:'🧤', stats:{m:14,r:198,avg:19.8,sr:118.0,w:0,eco:0}   },
        { id:'vv5', name:'Lalit Modi',      role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:12,r:312,avg:28.4,sr:128.0,w:0,eco:0}   },
        { id:'vv6', name:'Samir Mehta',     role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:14,r:22,avg:4.4,sr:72.0,w:16,eco:8.4}   },
        { id:'vv7', name:'Rahul Amin',      role:'Bowler',       bat:'Right-hand', bowl:'Left-arm Spin',      isCaptain:false, isWK:false, avatar:'🌀', stats:{m:13,r:17,avg:3.4,sr:68.0,w:14,eco:7.3}   },
        { id:'vv8', name:'Faizan Trivedi',  role:'All-rounder',  bat:'Left-hand',  bowl:'Left-arm Fast',      isCaptain:false, isWK:false, avatar:'⭐', stats:{m:12,r:189,avg:21.0,sr:122.0,w:8,eco:8.9}  },
        { id:'vv9', name:'Deven Chaudhary', role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:10,r:241,avg:26.8,sr:125.0,w:0,eco:0}   },
        { id:'vv10',name:'Vipul Nayak',     role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Leg-spin', isCaptain:false, isWK:false, avatar:'🌀', stats:{m:11,r:14,avg:2.8,sr:63.0,w:13,eco:7.6}   },
        { id:'vv11',name:'Jignesh Raval',   role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:9,r:8,avg:2.7,sr:57.0,w:9,eco:8.2}      },
        { id:'vv12',name:'Chetan Solanki',  role:'Batter',       bat:'Left-hand',  bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:8,r:198,avg:28.3,sr:134.0,w:0,eco:0}    },
        { id:'vv13',name:'Yuvraj Thakkar',  role:'All-rounder',  bat:'Right-hand', bowl:'Right-arm Off-spin', isCaptain:false, isWK:false, avatar:'⭐', stats:{m:7,r:112,avg:18.7,sr:114.0,w:6,eco:7.7}   },
        { id:'vv14',name:'Harsh Prajapati', role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:6,r:5,avg:2.5,sr:50.0,w:5,eco:9.1}      },
        { id:'vv15',name:'Maulik Panchal',  role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:5,r:143,avg:28.6,sr:131.0,w:0,eco:0}    },
      ]
    },
    {
      id: 'rajkot-riders',
      name: 'Rajkot Riders',
      shortName: 'RR',
      color: '#dc2626',
      color2: '#fef08a',
      emoji: '🏇',
      homeGround: 'Madhavrao Scindia Ground, Rajkot',
      captain: 'Bhavesh Modi',
      coach: 'Jayant Trivedi',
      titles: 1,
      titleYears: [2021],
      founded: 2020,
      desc: 'Rajkot Riders were the dominant force in the inaugural PCL season, capturing the 2021 title under Bhavesh Modi\'s aggressive leadership.',
      players: [
        { id:'rr1', name:'Bhavesh Modi',    role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:true,  isWK:false, avatar:'👑', stats:{m:14,r:534,avg:44.5,sr:154.0,w:0,eco:0}   },
        { id:'rr2', name:'Arpit Shah',      role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:14,r:398,avg:33.2,sr:141.0,w:0,eco:0}   },
        { id:'rr3', name:'Priyank Joshi',   role:'All-rounder',  bat:'Left-hand',  bowl:'Left-arm Fast',      isCaptain:false, isWK:false, avatar:'⭐', stats:{m:14,r:289,avg:26.3,sr:136.0,w:13,eco:8.1} },
        { id:'rr4', name:'Gaurav Patel',    role:'Wicket-keeper',bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:true,  avatar:'🧤', stats:{m:14,r:201,avg:20.1,sr:122.0,w:0,eco:0}   },
        { id:'rr5', name:'Siddharth Amin',  role:'Batter',       bat:'Right-hand', bowl:'Right-arm Off-spin', isCaptain:false, isWK:false, avatar:'🏏', stats:{m:13,r:321,avg:29.2,sr:130.0,w:2,eco:7.6} },
        { id:'rr6', name:'Tejas Mehta',     role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:14,r:27,avg:5.4,sr:81.0,w:19,eco:7.8}   },
        { id:'rr7', name:'Rishi Trivedi',   role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Leg-spin', isCaptain:false, isWK:false, avatar:'🌀', stats:{m:14,r:21,avg:4.2,sr:74.0,w:17,eco:7.0}   },
        { id:'rr8', name:'Kabir Chaudhary', role:'All-rounder',  bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'⭐', stats:{m:12,r:198,avg:22.0,sr:126.0,w:9,eco:8.4}  },
        { id:'rr9', name:'Yash Solanki',    role:'Bowler',       bat:'Right-hand', bowl:'Left-arm Fast',      isCaptain:false, isWK:false, avatar:'🎯', stats:{m:11,r:14,avg:2.8,sr:60.0,w:14,eco:8.0}   },
        { id:'rr10',name:'Deep Nayak',      role:'Batter',       bat:'Left-hand',  bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:10,r:234,avg:26.0,sr:124.0,w:0,eco:0}   },
        { id:'rr11',name:'Hiren Panchal',   role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Off-spin', isCaptain:false, isWK:false, avatar:'🌀', stats:{m:9,r:16,avg:3.2,sr:64.0,w:10,eco:7.3}    },
        { id:'rr12',name:'Krish Raval',     role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:8,r:178,avg:25.4,sr:128.0,w:0,eco:0}    },
        { id:'rr13',name:'Neel Prajapati',  role:'All-rounder',  bat:'Right-hand', bowl:'Right-arm Leg-spin', isCaptain:false, isWK:false, avatar:'⭐', stats:{m:7,r:123,avg:20.5,sr:119.0,w:5,eco:7.9}   },
        { id:'rr14',name:'Sagar Thakkar',   role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:6,r:8,avg:2.7,sr:53.0,w:7,eco:8.6}      },
        { id:'rr15',name:'Raj Modi',        role:'Batter',       bat:'Left-hand',  bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:5,r:134,avg:26.8,sr:138.0,w:0,eco:0}    },
      ]
    },
    {
      id: 'bhuj-blazers',
      name: 'Bhuj Blazers',
      shortName: 'BB',
      color: '#16a34a',
      color2: '#fcd34d',
      emoji: '🌪️',
      homeGround: 'Kutch Warriors Ground, Bhuj',
      captain: 'Sameer Chaudhary',
      coach: 'Vinay Solanki',
      titles: 0,
      titleYears: [],
      founded: 2020,
      desc: 'Bhuj Blazers bring the raw energy of Kutch to the PCL. Known for their fiery pace attack, they\'ve upset many top teams and are a dangerous opponent on any given day.',
      players: [
        { id:'bb1', name:'Sameer Chaudhary',role:'Batter',       bat:'Right-hand', bowl:'Right-arm Off-spin', isCaptain:true,  isWK:false, avatar:'👑', stats:{m:14,r:467,avg:38.9,sr:141.0,w:2,eco:7.7} },
        { id:'bb2', name:'Laksh Patel',     role:'Batter',       bat:'Left-hand',  bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:14,r:376,avg:31.3,sr:138.0,w:0,eco:0}   },
        { id:'bb3', name:'Dhruvil Shah',    role:'All-rounder',  bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'⭐', stats:{m:14,r:256,avg:23.3,sr:133.0,w:10,eco:8.7} },
        { id:'bb4', name:'Ankit Joshi',     role:'Wicket-keeper',bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:true,  avatar:'🧤', stats:{m:14,r:189,avg:18.9,sr:115.0,w:0,eco:0}   },
        { id:'bb5', name:'Yash Mehta',      role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:13,r:298,avg:27.1,sr:127.0,w:0,eco:0}   },
        { id:'bb6', name:'Jesal Amin',      role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:14,r:23,avg:4.6,sr:76.0,w:20,eco:8.0}   },
        { id:'bb7', name:'Parth Trivedi',   role:'Bowler',       bat:'Right-hand', bowl:'Left-arm Spin',      isCaptain:false, isWK:false, avatar:'🌀', stats:{m:13,r:15,avg:3.0,sr:65.0,w:15,eco:7.2}   },
        { id:'bb8', name:'Vatsal Modi',     role:'All-rounder',  bat:'Left-hand',  bowl:'Left-arm Fast',      isCaptain:false, isWK:false, avatar:'⭐', stats:{m:12,r:178,avg:19.8,sr:120.0,w:7,eco:8.8}  },
        { id:'bb9', name:'Harsh Nayak',     role:'Batter',       bat:'Left-hand',  bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:10,r:221,avg:24.6,sr:123.0,w:0,eco:0}   },
        { id:'bb10',name:'Kishan Solanki',  role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Leg-spin', isCaptain:false, isWK:false, avatar:'🌀', stats:{m:11,r:12,avg:2.4,sr:60.0,w:12,eco:7.4}   },
        { id:'bb11',name:'Om Panchal',      role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:9,r:9,avg:2.3,sr:53.0,w:9,eco:8.9}      },
        { id:'bb12',name:'Rihan Raval',     role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:8,r:187,avg:26.7,sr:130.0,w:0,eco:0}    },
        { id:'bb13',name:'Arjun Prajapati', role:'All-rounder',  bat:'Right-hand', bowl:'Right-arm Off-spin', isCaptain:false, isWK:false, avatar:'⭐', stats:{m:7,r:105,avg:17.5,sr:113.0,w:5,eco:7.6}   },
        { id:'bb14',name:'Dev Thakkar',     role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:6,r:6,avg:2.0,sr:46.0,w:6,eco:8.3}      },
        { id:'bb15',name:'Zeel Chaudhary',  role:'Batter',       bat:'Left-hand',  bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:5,r:128,avg:25.6,sr:133.0,w:0,eco:0}    },
      ]
    },
    {
      id: 'mehsana-mavericks',
      name: 'Mehsana Mavericks',
      shortName: 'MM',
      color: '#0d9488',
      color2: '#f0fdfa',
      emoji: '🦅',
      homeGround: 'North Gujarat Sports Hub, Mehsana',
      captain: 'Deepak Thakkar',
      coach: 'Mukesh Panchal',
      titles: 0,
      titleYears: [],
      founded: 2020,
      desc: 'Mehsana Mavericks are tactically the smartest team in the PCL. Captain Deepak Thakkar is known for his on-field chess moves that have left opposing teams baffled.',
      players: [
        { id:'mm1', name:'Deepak Thakkar',  role:'Batter',       bat:'Right-hand', bowl:'Right-arm Leg-spin', isCaptain:true,  isWK:false, avatar:'👑', stats:{m:14,r:487,avg:40.6,sr:143.0,w:6,eco:7.5} },
        { id:'mm2', name:'Rajiv Patel',     role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:14,r:401,avg:33.4,sr:137.0,w:0,eco:0}   },
        { id:'mm3', name:'Swapnil Shah',    role:'All-rounder',  bat:'Left-hand',  bowl:'Left-arm Spin',      isCaptain:false, isWK:false, avatar:'⭐', stats:{m:14,r:267,avg:24.3,sr:129.0,w:12,eco:7.3} },
        { id:'mm4', name:'Hardik Joshi',    role:'Wicket-keeper',bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:true,  avatar:'🧤', stats:{m:14,r:178,avg:17.8,sr:116.0,w:0,eco:0}   },
        { id:'mm5', name:'Dhaval Modi',     role:'Batter',       bat:'Left-hand',  bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:13,r:287,avg:26.1,sr:124.0,w:0,eco:0}   },
        { id:'mm6', name:'Krunal Amin',     role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:14,r:18,avg:3.6,sr:69.0,w:18,eco:8.2}   },
        { id:'mm7', name:'Manish Mehta',    role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Leg-spin', isCaptain:false, isWK:false, avatar:'🌀', stats:{m:13,r:14,avg:2.8,sr:63.0,w:16,eco:7.0}   },
        { id:'mm8', name:'Dhruv Trivedi',   role:'All-rounder',  bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'⭐', stats:{m:12,r:201,avg:22.3,sr:126.0,w:8,eco:8.6}  },
        { id:'mm9', name:'Samir Chaudhary', role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:10,r:231,avg:25.7,sr:122.0,w:0,eco:0}   },
        { id:'mm10',name:'Jay Solanki',     role:'Bowler',       bat:'Right-hand', bowl:'Left-arm Fast',      isCaptain:false, isWK:false, avatar:'🎯', stats:{m:11,r:11,avg:2.2,sr:58.0,w:13,eco:8.1}   },
        { id:'mm11',name:'Keval Nayak',     role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Off-spin', isCaptain:false, isWK:false, avatar:'🌀', stats:{m:9,r:9,avg:2.3,sr:53.0,w:9,eco:7.5}      },
        { id:'mm12',name:'Jeel Panchal',    role:'Batter',       bat:'Left-hand',  bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:8,r:193,avg:27.6,sr:132.0,w:0,eco:0}    },
        { id:'mm13',name:'Nishant Raval',   role:'All-rounder',  bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'⭐', stats:{m:7,r:112,avg:18.7,sr:118.0,w:5,eco:8.7}   },
        { id:'mm14',name:'Tejas Prajapati', role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:6,r:7,avg:2.3,sr:50.0,w:6,eco:8.4}      },
        { id:'mm15',name:'Vandan Thakkar',  role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:5,r:138,avg:27.6,sr:135.0,w:0,eco:0}    },
      ]
    },
    {
      id: 'gandhinagar-gladiators',
      name: 'Gandhinagar Gladiators',
      shortName: 'GG',
      color: '#4338ca',
      color2: '#c7d2fe',
      emoji: '⚔️',
      homeGround: 'Capital City Cricket Ground, Gandhinagar',
      captain: 'Harsh Prajapati',
      coach: 'Sunil Nayak',
      titles: 0,
      titleYears: [],
      founded: 2020,
      desc: 'Gandhinagar Gladiators represent the power of Gujarat\'s capital. A disciplined, military-like unit that plays tough, consistent cricket match after match.',
      players: [
        { id:'gg1', name:'Harsh Prajapati', role:'Batter',       bat:'Right-hand', bowl:'Right-arm Off-spin', isCaptain:true,  isWK:false, avatar:'👑', stats:{m:14,r:512,avg:42.7,sr:146.0,w:4,eco:7.6} },
        { id:'gg2', name:'Parth Patel',     role:'Batter',       bat:'Left-hand',  bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:14,r:421,avg:35.1,sr:139.0,w:0,eco:0}   },
        { id:'gg3', name:'Keyur Shah',      role:'All-rounder',  bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'⭐', stats:{m:14,r:278,avg:25.3,sr:135.0,w:11,eco:8.3} },
        { id:'gg4', name:'Bhavin Joshi',    role:'Wicket-keeper',bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:true,  avatar:'🧤', stats:{m:14,r:198,avg:19.8,sr:119.0,w:0,eco:0}   },
        { id:'gg5', name:'Darshan Modi',    role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:13,r:312,avg:28.4,sr:130.0,w:0,eco:0}   },
        { id:'gg6', name:'Chintan Amin',    role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:14,r:20,avg:4.0,sr:73.0,w:17,eco:7.9}   },
        { id:'gg7', name:'Rajan Mehta',     role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Leg-spin', isCaptain:false, isWK:false, avatar:'🌀', stats:{m:13,r:13,avg:2.6,sr:61.0,w:15,eco:7.1}   },
        { id:'gg8', name:'Vinay Trivedi',   role:'All-rounder',  bat:'Left-hand',  bowl:'Left-arm Spin',      isCaptain:false, isWK:false, avatar:'⭐', stats:{m:12,r:210,avg:23.3,sr:127.0,w:9,eco:7.4}  },
        { id:'gg9', name:'Kirit Chaudhary', role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:10,r:242,avg:26.9,sr:124.0,w:0,eco:0}   },
        { id:'gg10',name:'Umang Solanki',   role:'Bowler',       bat:'Right-hand', bowl:'Left-arm Fast',      isCaptain:false, isWK:false, avatar:'🎯', stats:{m:11,r:10,avg:2.0,sr:56.0,w:12,eco:8.0}   },
        { id:'gg11',name:'Vimal Nayak',     role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Off-spin', isCaptain:false, isWK:false, avatar:'🌀', stats:{m:9,r:8,avg:2.0,sr:52.0,w:8,eco:7.6}      },
        { id:'gg12',name:'Param Panchal',   role:'Batter',       bat:'Left-hand',  bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:8,r:197,avg:28.1,sr:133.0,w:0,eco:0}    },
        { id:'gg13',name:'Manish Raval',    role:'All-rounder',  bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'⭐', stats:{m:7,r:118,avg:19.7,sr:116.0,w:5,eco:8.5}   },
        { id:'gg14',name:'Chirag Prajapati',role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:6,r:7,avg:2.3,sr:49.0,w:6,eco:8.8}      },
        { id:'gg15',name:'Rishit Thakkar',  role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:5,r:131,avg:26.2,sr:136.0,w:0,eco:0}    },
      ]
    },
    {
      id: 'patan-panthers',
      name: 'Patan Panthers',
      shortName: 'PP',
      color: '#9f1239',
      color2: '#fde68a',
      emoji: '🐆',
      homeGround: 'Heritage City Ground, Patan',
      captain: 'Ravi Choksi',
      coach: 'Dilip Raval',
      titles: 0,
      titleYears: [],
      founded: 2020,
      desc: 'Patan Panthers are the dark horses of the PCL. Rooted in Gujarat\'s ancient city, they play with a fighting spirit and a never-say-die attitude that makes every match thrilling.',
      players: [
        { id:'pp1', name:'Ravi Choksi',     role:'Batter',       bat:'Right-hand', bowl:'Right-arm Off-spin', isCaptain:true,  isWK:false, avatar:'👑', stats:{m:14,r:476,avg:39.7,sr:140.0,w:3,eco:7.8} },
        { id:'pp2', name:'Sanjay Patel',    role:'Batter',       bat:'Left-hand',  bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:14,r:389,avg:32.4,sr:136.0,w:0,eco:0}   },
        { id:'pp3', name:'Viral Shah',      role:'All-rounder',  bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'⭐', stats:{m:14,r:245,avg:22.3,sr:131.0,w:12,eco:8.4} },
        { id:'pp4', name:'Nilesh Joshi',    role:'Wicket-keeper',bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:true,  avatar:'🧤', stats:{m:14,r:178,avg:17.8,sr:114.0,w:0,eco:0}   },
        { id:'pp5', name:'Rajesh Modi',     role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:13,r:298,avg:27.1,sr:126.0,w:0,eco:0}   },
        { id:'pp6', name:'Ketul Amin',      role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:14,r:19,avg:3.8,sr:71.0,w:19,eco:7.7}   },
        { id:'pp7', name:'Tejas Mehta',     role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Leg-spin', isCaptain:false, isWK:false, avatar:'🌀', stats:{m:13,r:15,avg:3.0,sr:65.0,w:17,eco:7.2}   },
        { id:'pp8', name:'Ansh Trivedi',    role:'All-rounder',  bat:'Left-hand',  bowl:'Left-arm Fast',      isCaptain:false, isWK:false, avatar:'⭐', stats:{m:12,r:189,avg:21.0,sr:121.0,w:8,eco:8.7}  },
        { id:'pp9', name:'Virat Chaudhary', role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:10,r:221,avg:24.6,sr:123.0,w:0,eco:0}   },
        { id:'pp10',name:'Sahil Solanki',   role:'Bowler',       bat:'Right-hand', bowl:'Left-arm Spin',      isCaptain:false, isWK:false, avatar:'🌀', stats:{m:11,r:10,avg:2.0,sr:57.0,w:12,eco:7.3}   },
        { id:'pp11',name:'Parth Nayak',     role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:9,r:8,avg:2.0,sr:52.0,w:9,eco:8.2}      },
        { id:'pp12',name:'Zeal Panchal',    role:'Batter',       bat:'Left-hand',  bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:8,r:189,avg:27.0,sr:131.0,w:0,eco:0}    },
        { id:'pp13',name:'Raj Raval',       role:'All-rounder',  bat:'Right-hand', bowl:'Right-arm Off-spin', isCaptain:false, isWK:false, avatar:'⭐', stats:{m:7,r:108,avg:18.0,sr:114.0,w:5,eco:7.7}   },
        { id:'pp14',name:'Bharat Prajapati',role:'Bowler',       bat:'Right-hand', bowl:'Right-arm Fast',     isCaptain:false, isWK:false, avatar:'🎯', stats:{m:6,r:6,avg:2.0,sr:48.0,w:6,eco:8.5}      },
        { id:'pp15',name:'Manan Choksi',    role:'Batter',       bat:'Right-hand', bowl:'N/A',                isCaptain:false, isWK:false, avatar:'🏏', stats:{m:5,r:136,avg:27.2,sr:134.0,w:0,eco:0}    },
      ]
    }
  ],

  /* ========================================
     MATCHES
  ======================================== */
  matches: [
    // --- COMPLETED ---
    { id:'m1',  num:1,  team1:'anand-arrows',         team2:'surat-smashers',        date:'2025-03-15', time:'14:00', venue:'Anand Sports Complex',       status:'completed', winner:'anand-arrows',         result:'Anand Arrows won by 45 runs',             score1:'182/6 (20)', score2:'137/9 (20)' },
    { id:'m2',  num:2,  team1:'rajkot-riders',         team2:'vadodara-valiants',     date:'2025-03-16', time:'14:00', venue:'Madhavrao Scindia Ground',    status:'completed', winner:'rajkot-riders',         result:'Rajkot Riders won by 5 wickets',          score1:'148/5 (18.4)',score2:'147/8 (20)' },
    { id:'m3',  num:3,  team1:'bhuj-blazers',          team2:'mehsana-mavericks',     date:'2025-03-17', time:'14:00', venue:'Kutch Warriors Ground',       status:'completed', winner:'bhuj-blazers',          result:'Bhuj Blazers won by 23 runs',             score1:'164/7 (20)', score2:'141/9 (20)' },
    { id:'m4',  num:4,  team1:'gandhinagar-gladiators',team2:'patan-panthers',        date:'2025-03-18', time:'14:00', venue:'Capital City Cricket Ground', status:'completed', winner:'gandhinagar-gladiators', result:'Gandhinagar Gladiators won by 8 wickets', score1:'112/2 (13.1)',score2:'111/8 (20)' },
    { id:'m5',  num:5,  team1:'anand-arrows',          team2:'bhuj-blazers',          date:'2025-03-20', time:'14:00', venue:'Anand Sports Complex',        status:'completed', winner:'anand-arrows',          result:'Anand Arrows won by 12 runs',             score1:'156/6 (20)', score2:'144/7 (20)' },
    { id:'m6',  num:6,  team1:'surat-smashers',        team2:'rajkot-riders',         date:'2025-03-21', time:'14:00', venue:'Diamond City Arena',          status:'completed', winner:'surat-smashers',        result:'Surat Smashers won by 7 wickets',         score1:'143/3 (17.2)',score2:'142/6 (20)' },
    { id:'m7',  num:7,  team1:'mehsana-mavericks',     team2:'gandhinagar-gladiators',date:'2025-03-22', time:'14:00', venue:'North Gujarat Sports Hub',    status:'completed', winner:'mehsana-mavericks',     result:'Mehsana Mavericks won by 3 runs',         score1:'168/5 (20)', score2:'165/8 (20)' },
    { id:'m8',  num:8,  team1:'patan-panthers',        team2:'vadodara-valiants',     date:'2025-03-23', time:'14:00', venue:'Heritage City Ground',        status:'completed', winner:'patan-panthers',        result:'Patan Panthers won by 4 wickets',         score1:'154/6 (18.3)',score2:'153/7 (20)' },
    { id:'m9',  num:9,  team1:'anand-arrows',          team2:'rajkot-riders',         date:'2025-03-25', time:'14:00', venue:'Anand Sports Complex',        status:'completed', winner:'anand-arrows',          result:'Anand Arrows won by 67 runs',             score1:'198/4 (20)', score2:'131/10 (18.2)'},
    { id:'m10', num:10, team1:'surat-smashers',        team2:'bhuj-blazers',          date:'2025-03-26', time:'14:00', venue:'Diamond City Arena',          status:'completed', winner:'surat-smashers',        result:'Surat Smashers won by 2 wickets',         score1:'161/8 (19.4)',score2:'160/6 (20)' },
    { id:'m11', num:11, team1:'gandhinagar-gladiators',team2:'vadodara-valiants',     date:'2025-03-27', time:'14:00', venue:'Capital City Cricket Ground', status:'completed', winner:'gandhinagar-gladiators', result:'Gandhinagar Gladiators won by 18 runs',   score1:'173/6 (20)', score2:'155/8 (20)' },
    { id:'m12', num:12, team1:'patan-panthers',        team2:'mehsana-mavericks',     date:'2025-03-28', time:'14:00', venue:'Heritage City Ground',        status:'completed', winner:'patan-panthers',        result:'Patan Panthers won by 33 runs',           score1:'178/5 (20)', score2:'145/9 (20)' },

    // --- UPCOMING ---
    { id:'m13', num:13, team1:'anand-arrows',          team2:'mehsana-mavericks',     date:'2025-04-02', time:'14:00', venue:'Anand Sports Complex',        status:'upcoming',  winner:null, result:null, score1:null, score2:null },
    { id:'m14', num:14, team1:'surat-smashers',        team2:'patan-panthers',        date:'2025-04-02', time:'18:00', venue:'Diamond City Arena',          status:'upcoming',  winner:null, result:null, score1:null, score2:null },
    { id:'m15', num:15, team1:'rajkot-riders',         team2:'bhuj-blazers',          date:'2025-04-03', time:'14:00', venue:'Madhavrao Scindia Ground',    status:'upcoming',  winner:null, result:null, score1:null, score2:null },
    { id:'m16', num:16, team1:'gandhinagar-gladiators',team2:'mehsana-mavericks',     date:'2025-04-03', time:'18:00', venue:'Capital City Cricket Ground', status:'upcoming',  winner:null, result:null, score1:null, score2:null },
    { id:'m17', num:17, team1:'vadodara-valiants',     team2:'bhuj-blazers',          date:'2025-04-05', time:'14:00', venue:'Sayaji Baug Stadium',         status:'upcoming',  winner:null, result:null, score1:null, score2:null },
    { id:'m18', num:18, team1:'patan-panthers',        team2:'rajkot-riders',         date:'2025-04-05', time:'18:00', venue:'Heritage City Ground',        status:'upcoming',  winner:null, result:null, score1:null, score2:null },
    { id:'m19', num:19, team1:'anand-arrows',          team2:'gandhinagar-gladiators',date:'2025-04-07', time:'14:00', venue:'Anand Sports Complex',        status:'upcoming',  winner:null, result:null, score1:null, score2:null },
    { id:'m20', num:20, team1:'surat-smashers',        team2:'vadodara-valiants',     date:'2025-04-07', time:'18:00', venue:'Diamond City Arena',          status:'upcoming',  winner:null, result:null, score1:null, score2:null },
  ],

  /* ========================================
     DEFAULT POINTS TABLE
  ======================================== */
  pointsTable: [
    { teamId:'anand-arrows',         p:3, w:3, l:0, nr:0, pts:6,  nrr:+1.23 },
    { teamId:'patan-panthers',       p:2, w:2, l:0, nr:0, pts:4,  nrr:+0.64 },
    { teamId:'surat-smashers',       p:3, w:2, l:1, nr:0, pts:4,  nrr:+0.58 },
    { teamId:'gandhinagar-gladiators',p:2,w:2, l:0, nr:0, pts:4,  nrr:+0.31 },
    { teamId:'rajkot-riders',        p:2, w:1, l:1, nr:0, pts:2,  nrr:+0.12 },
    { teamId:'bhuj-blazers',         p:2, w:1, l:1, nr:0, pts:2,  nrr:-0.21 },
    { teamId:'mehsana-mavericks',    p:2, w:1, l:1, nr:0, pts:2,  nrr:-0.34 },
    { teamId:'vadodara-valiants',    p:3, w:0, l:3, nr:0, pts:0,  nrr:-1.67 },
  ],

  /* ========================================
     DEFAULT LIVE MATCH STATE (null = no live match)
  ======================================== */
  liveMatch: null,

  /* ========================================
     TOURNAMENT INFO
  ======================================== */
  tournament: {
    name: 'Patidar Cricket League 2025',
    shortName: 'PCL 2025',
    season: 5,
    startDate: '2025-03-15',
    endDate: '2025-05-10',
    venue: 'Gujarat, India',
    totalTeams: 8,
    totalMatches: 28,
    sponsor: 'Patidar Samaj Foundation'
  }
};
